import { createHash } from 'node:crypto'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

/**
 * Emits the service worker at build time so its precache list holds the real
 * content-hashed asset names, and its cache name changes whenever the bundle
 * does (which is what evicts the previous version's caches).
 *
 * Strategies:
 *   - /api, /socket.io, /metrics : never touched. Auth, live progress and
 *     range-request video streaming must not be served from a cache.
 *   - navigations                : network-first, falling back to the cached
 *     app shell so the PWA opens offline instead of showing a browser error.
 *   - hashed build assets        : cache-first (the hash makes them immutable).
 *   - other same-origin GETs     : stale-while-revalidate.
 */
function serviceWorker(): Plugin {
  return {
    name: 'downlee-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const precache = [
        '/',
        '/index.html',
        '/manifest.webmanifest',
        '/favicon.png',
        '/apple-touch-icon.png',
        '/icon-192.png',
        '/icon-512.png',
        ...Object.keys(bundle)
          .filter((name) => /\.(js|css|woff2?)$/.test(name))
          .map((name) => `/${name}`),
      ]
      const version = createHash('sha256')
        .update(precache.join('|'))
        .digest('hex')
        .slice(0, 12)

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(version, precache),
      })
    },
  }
}

function swSource(version: string, precache: string[]) {
  return `// Generated by vite.config.ts - do not edit.
const CACHE = 'downlee-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

// Requests that must always hit the network: authenticated API calls, the
// Socket.IO transport, Prometheus, and media streams (range requests).
const NETWORK_ONLY = [/^\\/api\\//, /^\\/socket\\.io\\//, /^\\/metrics$/];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // addAll is all-or-nothing; add individually so one 404 can't leave the
      // app with no cached shell at all.
      .then((cache) => Promise.all(
        PRECACHE.map((url) => cache.add(url).catch(() => {}))
      ))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NETWORK_ONLY.some((re) => re.test(url.pathname))) return;

  // SPA navigations: fresh when online, cached shell when not.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        const cache = await caches.open(CACHE);
        cache.put('/index.html', response.clone());
        return response;
      } catch {
        const cached = await caches.match('/index.html');
        return cached || Response.error();
      }
    })());
    return;
  }

  // Content-hashed build output is immutable: serve from cache when present.
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith((async () => {
      const cached = await caches.match(request);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) (await caches.open(CACHE)).put(request, response.clone());
      return response;
    })());
    return;
  }

  // Everything else same-origin: serve cache, refresh in the background.
  event.respondWith((async () => {
    const cached = await caches.match(request);
    const network = fetch(request).then(async (response) => {
      if (response.ok) (await caches.open(CACHE)).put(request, response.clone());
      return response;
    }).catch(() => cached);
    return cached || network;
  })());
});
`
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(), serviceWorker()],
  server: {
    host: '0.0.0.0',
    port: 5173,
  },
})
